language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

script:
  - make test
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

after_success:
  - travis_retry php vendor/bin/coveralls -v
